export class HttpErrors {
    static INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS";
    static INCORRECT_CODE = "INCORRECT_CODE";
    static USER_EMAIL_IN_USED = "USER_EMAIL_IN_USED";
    static SERVER_ERROR = "SERVER_ERROR";
    static NOT_ACCEPTABLE = "NOT_ACCEPTABLE";
    static NOT_FOUND = "NOT_FOUND";
    static EMAIL_DOESNT_EXITS = "EMAIL_DOESNT_EXITS";
    static CODE_EXPIRE = "CODE_EXPIRE";
    static RECORD_IN_USE = "RECORD_IN_USE";
    static EXPECTATION_FAILED = "EXPECTATION_FAILED";
    static CONFLICT = "CONFLICT";
    static NOT_PAYMENT_COMPLETE = "NOT_PAYMENT_COMPLETE";
    static PAYMENT_ACTION_REQUIREMENT = "PAYMENT_ACTION_REQUIREMENT";
    static INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK";
}